apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-test-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-python
spec:
  params:
    - name: source-url
    - name: source-revision
    - name: source-sub-path
      default: ""
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: source-sub-path
          value: $(params.source-sub-path)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
          - name: source-sub-path
        steps:
          - name: test
            #image: continuumio/miniconda3
            #image: openvino/ubuntu22_dev:latesta
            image: mwrightpivotal/cv-stack-build:1.0
            script: |-
              set -ex
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m

              conda init bash
              . /root/.bashrc
              conda env create -f environment.yml
              conda activate py39
              python -m pip install --upgrade pip
              python -m pip install pytest

              export PATH=/home/openvino/.local/bin:$PATH
              pytest
